concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.ref }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.4
    - continue-on-error: true
      name: Run unit tests
      run: ./gradlew testDebugUnitTest --stacktrace
    - continue-on-error: true
      name: Assemble library
      run: ./gradlew assembleRelease
name: Pull requests
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
